name: Build Docker Image 

on:
  push:
    branches:
      - main # adjust this to your main branch name

env:
  IP_ADDRESS: ${{ secrets.IP_ADDRESS }}
  AWS_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        labels: [1, 2]  # Adjust the number of labels based on the number of jobs

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Create and Run Docker Container
        run: |
          label="${{ matrix.labels }}"
          echo "Creating and running container with label $label"

          # Create the container
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@"${{ env.IP_ADDRESS }}" \
            "sudo docker run -d --env ORGANIZATION='${{ github.repository }}' \
            --env ACCESS_TOKEN='${{ secrets.ACCESS_TOKEN }}' \
            --env LABEL='$label' \
            --name runner-$label \
            -v /var/run/docker.sock:/var/run/docker.sock \  # Mount the Docker socket
            anjanar17/my-image-name:latest"
            # anjanar17/my-image-name:latest"

          # Run your specific job inside the container (adjust the command as needed)
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@"${{ env.IP_ADDRESS }}" \
            "sudo docker exec runner-$label echo 'Hello from container $label'"
